version: "3.9"
name: algo_deploy

services:
  web:
    image: "algo_deploy:latest"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/code
